version: 2.1
jobs:
  build:
    docker:
      - image: fr3akyphantom/droid-builder:edge
    environment:
      MANIFEST_BRANCH: 'halibut'
      PBRP_BRANCH: 'pbrp-7.1' # OPTIONAL:: If not default 'android-9.0', define other bootable_recovery branch
      VERSION: '3.0.0'
      MAINTAINER: 'Daniel'
      VENDOR: 'MyPhone'
      CODENAME: 'halibut'
      FLAVOR: 'eng'
      TEST_BUILD: 'true'
      # PB_OFFICIAL: "true"
      # EXTRA_CMD: "" # OPTIONAL:: MUST USE DOUBLE-QUOTE
      # PB_ENGLISH: "true" # OPTIONAL:: If you want only English Language
      CHANGELOG: |
        - Initial Build
    working_directory: /home/builder/pitchblack
    steps:
      - run:
          name: AIO Build
          command: |
            wget -q https://raw.githubusercontent.com/PitchBlackRecoveryProject/vendor_utils/pb/build.sh
            source build.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
        filters:
          branches:
             only: 'halibut'
          context: personal-envs
